local M = {
  blankline = require("plugins.configs.blankline"),
  bufferline = require("plugins.configs.bufferline"),
  catppuccin = require("plugins.configs.catppuccin"),
  cmp = require("plugins.configs.cmp"),
  conform = require("plugins.configs.conform"),
  copilot = require("plugins.configs.copilot"),
  dashboard = require("plugins.configs.dashboard"),
  dressing = require("plugins.configs.dressing"),
  flash = require("plugins.configs.flash"),
  gitsign = require("plugins.configs.gitsign"),
  gpt = require("plugins.configs.gpt"),
  lspconfig = require("plugins.configs.lspconfig"),
  lualine = require("plugins.configs.lualine"),
  noice = require("plugins.configs.noice"),
  notify = require("plugins.configs.notify"),
  nvimtree = require("plugins.configs.nvimtree"),
  rainbow = require("plugins.configs.rainbow"),
  telescope = require("plugins.configs.telescope"),
  treesitter = require("plugins.configs.treesitter"),
  whichkey = require("plugins.configs.whichkey"),
  devicon = require("plugins.configs.devicon"),
  copilot_status = require("plugins.configs.copilot_status"),
  hop = require("plugins.configs.hop"),
  lazy = require("plugins.configs.lazy"),
}

return M
