local M = {
  blankline = require("plugins.configs.blankline"),
  bufferline = require("plugins.configs.bufferline"),
  catppuccin = require("plugins.configs.catppuccin"),
  cmp = require("plugins.configs.cmp"),
  conform = require("plugins.configs.conform"),
  copilot = require("plugins.configs.copilot"),
  dressing = require("plugins.configs.dressing"),
  flash = require("plugins.configs.flash"),
  gitsign = require("plugins.configs.gitsign"),
  gpt = require("plugins.configs.gpt"),
  lspconfig = require("plugins.configs.lspconfig"),
  lualine = require("plugins.configs.lualine"),
  noice = require("plugins.configs.noice"),
  notify = require("plugins.configs.notify"),
  nvimtree = require("plugins.configs.nvimtree"),
  rainbow = require("plugins.configs.rainbow"),
  telescope = require("plugins.configs.telescope"),
  treesitter = require("plugins.configs.treesitter"),
  whichkey = require("plugins.configs.whichkey"),
  devicon = require("plugins.configs.devicon"),
  copilot_status = require("plugins.configs.copilot_status"),
  hop = require("plugins.configs.hop"),
  lazy = require("plugins.configs.lazy"),
  octo = require("plugins.configs.octo"),
  projections = require("plugins.configs.projections"),
  terms = require("plugins.configs.terms"),
  dashboard = require("plugins.configs.dashboard"),
  mason = require("plugins.configs.mason"),
  material = require("plugins.configs.material"),
  harpoon = require("plugins.configs.harpoon"),
  illuminate = require("plugins.configs.illuminate"),
  mini_files = require("plugins.configs.mini_files"),
  neotest = require("plugins.configs.neotest"),
  mini_ai = require("plugins.configs.mini_ai"),
}

return M
