local configs = require("plugins.configs")
local plugins = {
  { "nvim-lua/plenary.nvim",               lazy = true, },
  { "wakatime/vim-wakatime",               lazy = false },
  { "nvim-pack/nvim-spectre",              cmd = "Spectre" },
  { "echasnovski/mini.bufremove",          event = "BufReadPre" },
  { "windwp/nvim-ts-autotag",              event = "VeryLazy" },
  { "andymass/vim-matchup",                event = "VeryLazy" },
  { "vim-ruby/vim-ruby",                   event = "BufReadPre" },
  { "tpope/vim-haml",                      event = "VeryLazy" },
  { "thoughtbot/vim-rspec",                event = "VeryLazy" },
  { "sindrets/diffview.nvim",              event = "VeryLazy" },
  { "vim-test/vim-test",                   event = "VeryLazy" },
  { "tpope/vim-rails",                     event = "VeryLazy" },
  { "mattn/emmet-vim",                     event = "VeryLazy" },
  { "rhysd/clever-f.vim",                  event = "VeryLazy" },
  { "nvim-tree/nvim-web-devicons",         config = configs.devicon },
  { "lukas-reineke/indent-blankline.nvim", event = { "BufReadPre", "BufNewFile" }, config = configs.blankline, },
  {
    "NeogitOrg/neogit",
    cmd = "Neogit",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "sindrets/diffview.nvim",
      "ibhagwan/fzf-lua",
    },
    config = true,
  },
  { "mg979/vim-visual-multi",          event = "VeryLazy",         branch = "master" },
  { "folke/persistence.nvim",          event = "BufReadPre",       opts = {} },
  { "lewis6991/gitsigns.nvim",         config = configs.gitsign,   event = { "BufReadPre", "BufNewFile" }, },
  { "nvim-tree/nvim-tree.lua",         config = configs.nvimtree,  cmd = { "NvimTreeToggle", "NvimTreeFocus" }, },
  { 'stevearc/dressing.nvim',          opts = {},                  config = configs.dressing },
  { "rcarriga/nvim-notify",            event = "VeryLazy",         config = configs.notify },
  { "stevearc/conform.nvim",           lazy = true,                config = configs.conform },
  { "HiPhish/rainbow-delimiters.nvim", event = "BufReadPre",       config = configs.rainbow },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate",        config = configs.treesitter },
  { "nvim-telescope/telescope.nvim",   cmd = "Telescope",          config = configs.telescope },
  { "akinsho/bufferline.nvim",         event = "BufReadPre",       config = configs.bufferline },
  { "max397574/better-escape.nvim",    event = "InsertEnter",      config = function() require("better_escape").setup() end, },
  { "numToStr/Comment.nvim",           event = "BufReadPre",       config = function() require("Comment").setup() end, },
  { "kylechui/nvim-surround",          event = "BufReadPre",       config = function() require("nvim-surround").setup({}) end, },
  { "declancm/cinnamon.nvim",          event = "VeryLazy",         config = function() require("cinnamon").setup() end, },
  { "tiagovla/scope.nvim",             event = "VeryLazy",         config = function() require("scope").setup({}) end },
  { "NvChad/nvim-colorizer.lua",       event = "VeryLazy",         opts = { user_default_options = { names = false } }, },
  { "neovim/nvim-lspconfig",           config = configs.lspconfig, event = { "BufReadPre", "BufNewFile" }, },
  {
    "stevearc/aerial.nvim",
    event = "VeryLazy",
    opts = {},
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
  },
  { "phaazon/hop.nvim",         branch = "v2",        cmd = "HopWord",       config = configs.hop, },
  { "folke/flash.nvim",         event = "VeryLazy",   opts = {},             keys = configs.flash },
  { "zbirenbaum/copilot.lua",   cmd = "Copilot",      event = "InsertEnter", config = configs.copilot },
  { "folke/todo-comments.nvim", event = "BufReadPre", opts = {},             dependencies = { "nvim-lua/plenary.nvim" } },
  { "catppuccin/nvim",          name = "catppuccin",  lazy = false,          config = configs.catppuccin },
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    config = configs.lualine,
    dependencies = { 'nvim-tree/nvim-web-devicons' }
  },
  {
    "folke/trouble.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {},
    cmd = "Trouble",
    config = function() require("trouble").setup() end,
  },
  {
    "hrsh7th/nvim-cmp",
    event = "InsertEnter",
    dependencies = configs.cmp.dependencies,
    config = configs.cmp.config
  },
  {
    "glepnir/dashboard-nvim",
    config = configs.dashboard,
    event = "VimEnter",
    dependencies = { "nvim-tree/nvim-web-devicons" },
  },
  {
    "jonahgoldwastaken/copilot-status.nvim",
    dependencies = { "zbirenbaum/copilot.lua" },
    event = "BufReadPost",
    config = configs.copilot_status,
  },
  {
    "jackMort/ChatGPT.nvim",
    event = "VeryLazy",
    config = configs.gpt,
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim", },
  },
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {},
    dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
    config = configs.noice
  },
  {
    "folke/which-key.nvim",
    keys = { "<leader>", "<c-r>", "<c-w>", '"', "'", "`", "c", "v", "g" },
    cmd = "WhichKey",
    config = configs.whichkey,
  },
}

require("lazy").setup(plugins, configs.lazy)
